name: backend-cd

on:
  pull_request:
    branches: 
    - master
    paths: ./starter/backend
  workflow_dispatch:

env:
  PYTHON_VER: 3.11

jobs:
  run-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: prepare python
      uses: actions/setup-python@v4
      with: 
        python-version: ${{env.PYTHON_VER}}
    - name: Install
      run: | 
        pip install pipenv
        pipenv install && pip install flake8
    - name: Run tests
      run: |
        pipenv run test

  run-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: prepare python
      uses: actions/setup-python@v4
      with: 
        python-version: ${{env.PYTHON_VER}}
    - name: Install
      run: | 
        pip install pipenv
        pipenv install
    - name: Run lint
      run: |
        pipenv run lint

  deploy-app:
    needs: [run-test, run-lint]
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./starter/backend
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Install
      run: | 
        pip install pipenv && pip install flake8
        pipenv install

    # - name: build app
    #   run: docker build --build-arg=REACT_APP_MOVIE_API_URL=${{env.REACT_APP_MOVIE_API_URL}} .
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: "true"
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name cluster
    - name: Run setup init.sh
      working-directory: ./setup
      run: ./init.sh || true
    - name: Cache Docker image
      uses: actions/cache@v3
      with:
        path: ~/docker-cache
        key: docker-${{ github.sha }}-backend