name: front-end-ci

on:
  pull_request:
    branches: 
    - master
    paths: ./starter/frontend
  workflow_dispatch:

env:
  ENV_VAR: dev
  NODE_VER: 20
  REACT_APP_MOVIE_API_URL: 'http://localhost:5000'

jobs:
  run-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: prepare node
      uses: actions/setup-node@v3
      with: 
        node-version: ${{env.NODE_VER}}
    
    - name: Install, Test
      working-directory: ./starter/frontend
      run: | 
        npm install -f
        CI=true npm run test

  run-lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: prepare node
      uses: actions/setup-node@v3
      with: 
        node-version: ${{env.NODE_VER}}
    
    - name: Install, Lint
      working-directory: ./starter/frontend
      run: | 
        npm ci
        npm run lint --fix

  build-app:
    needs: [run-test, run-lint]
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: build app
      working-directory: ./starter/frontend
      run: docker build --build-arg=REACT_APP_MOVIE_API_URL=${{env.REACT_APP_MOVIE_API_URL}} .